# Generated by Django 3.2.18 on 2023-05-18 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_comment_movie_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='movie_like_users',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_like_users',
            field=models.ManyToManyField(related_name='like_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
