# Generated by Django 3.2.18 on 2023-05-18 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20230518_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_like_users',
            new_name='like_users',
        ),
    ]
